server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Esto redirige cualquier ruta desconocida al index.html para que React Router la maneje
        try_files $uri $uri/ /index.html;
    }

    # Opcional: Cache de archivos estáticos para que cargue más rápido
    location ~* \.(?:ico|css|js|gif|jpe?g|png)$ {
        expires 30d;
        add_header Cache-Control "public";
        root /usr/share/nginx/html;
    }
}